get:
  tags:
  - Admin
  summary: Reads app configs
  description: |
    If version is provided, the app config for the highest version that is equal to or less than this value will be returned as the only item in the list.
    Otherwise it will return a list of all app config versions for the given app_type_id. If org_id is provided, the configs for that organization will
    be returned, otherwise the default configs will be returned.

    **Auth:** Requires admin access token with `get_app-configs`, `update_app-configs`, `delete_app-configs`, or `all_app-configs` permission
  security:
    - bearerAuth: []
  parameters:
    - name: app_type_id
      in: query
      required: true
      style: form
      explode: false
      schema:
        type: string
    - name: org_id
      in: query
      style: form
      explode: false
      schema:
        type: string
    - name: version
      in: query
      style: form
      explode: false
      schema:
        type: string
  responses:
    200:
      description: successfully read app configuration
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: "../../schemas/application/ApplicationConfig.yaml"
    400:
      description: Bad request.
    401:
      description: Unauthorized
    500:
      description: Internal error
post:
  tags:
  - Admin
  summary: Creates app configs
  description: |
    Creates a new app config

    **Auth:** Requires admin access token with `update_app-configs` or `all_app-configs` permission
  security:
    - bearerAuth: []
  requestBody:
    description: New app configs
    content:
      application/json:
        schema:
          $ref: "../../schemas/application/ApplicationConfig.yaml"
        example:
          version: "1.0.1"
          app_type_id: "7e037f2d-b423-4b4d-a1bc-18507f81c6d1"
          org_id: "0a2eff20-e2cd-11eb-af68-60f81db5ecc0"
          data: {}
    required: true
  responses:
    200:
      description: Success
      content:
        text/plain:
          schema:
            type: string
            example: Success
    400:
      description: Bad request
    401:
      description: Unauthorized
    500:
      description: Internal error